spatie/simple-excel

README.md
If the file you are reading does not contain a title row, then you should use the `noHeaderRow()` method.
=> Typo from 'than' to 'then'

README.md
Fixes typos in the `box/spout` package name
=> Fix box/spout typos

README.md
Like SimpleExcelWriter, SimpleExcelReader also uses the `create` method instead of `open` when setting a file path.
=> Correct SimpleExcelReader file loading method.

README.md, src/SimpleExcelReader.php, tests/SimpleExcelReaderTest.php
Closes #34 
Instead of `offset` and `limit`, I used `take` and `skip` to follow the conventions from LazyCollections.
=> Add 'take' and 'skip' functions to reader

README.md, src/SimpleExcelWriter.php
This PR adds a method for Styling the Header Row. In the current implementation styling only applies for non-header rows.
=> Add Header Styling Method

README.md, src/SimpleExcelReader.php, src/SimpleExcelWriter.php, tests/SimpleExcelReaderTest.php, tests/SimpleExcelWriterTest.php
I ran into a situation where I needed to set the file type for the writer manually. This PR adds an optional 2nd argument to both the Reader and Writer, so it's possible to set the type when it cannot be determined from the filename.
A concrete use-case is when trying to read from or write to the PHP input/output stream.
In my specific scenario, even though this package has built-in support for stream downloads, it didn't work inside a Laravel Livewire component, which expected a Laravel StreamDownload. I had to be able to write to the output stream, but since the stream name can't contain a file extension, I needed to specify the type manually. Here's how it would work with this PR in place:
```php
return response()->streamDownload(function () use ($builder) {
$writer = …
```
=> Allow setting the writer/reader type manually

src/SimpleExcelWriter.php
Allow to fluently set the headerstyle; e.g.
```php
return SimpleExcelWriter::streamDownload($outputFilename)
->setHeaderStyle($style)
->addRows($rows)
->toBrowser();
```
... instead of...
```php
$writer = SimpleExcelWriter::streamDownload($outputFilename);
$writer->setHeaderStyle($style);
return $writer
->addRows($rows)
->toBrowser();
```
=> use setHeaderStyle fluently

README.md, src/SimpleExcelWriter.php, tests/SimpleExcelWriterTest.php, tests/__snapshots__/files/SimpleExcelWriterTest__it_can_write_a_csv_without_bom__1.csv
This was the first pass on enabling this functionality, and closely mirrors what I had in the discussion notes.
I would wonder if potentially a shorthand would be helpful, like adding an explicit method instead like:
`createWithoutBOM($path, $type)`
With the current code changes, it'd be as simple as just calling create with a pre-defined callback.
This way it would keep the clean method signature set, but at least there's a start here for further more concrete discussion.
=> enable disabling BOM on writer

README.md, src/SimpleExcelReader.php, tests/SimpleExcelReaderTest.php, tests/stubs/headers-not-snake-case.csv
This PR adds a new method that allows the conversion of headers to snake_case format.
```csv
Email,First Name,Last Name
john@example.com,john,doe
mary-jane@example.com,mary jane,doe
```
```php
$rows = SimpleExcelReader::create($pathToCsv)
->headersToSnakeCase()
->getRows()
->each(function(array $rowProperties) {
// rowProperties converted to snake_case
// ['email' => 'john@example', 'first_name' => 'John', 'last_name' => 'doe']
});
```
Laravel Excel 2 automatically converts all the headers to snake_case and I wanted to keep the same behaviour so users don't have to update any of the import templates. I am currently migrating to Simple Excel as I didn't like the latest version of Laravel Excel (too much boilerplate for simple tasks). Hope this can be helpful for others in the same …
=> Add option to convert headers to snake_case format.

README.md, src/SimpleExcelReader.php, tests/SimpleExcelReaderTest.php
PR for #51.
Love this package, and thanks for all the value you've added to the community (Laravel Beyond Crud has had a huge impact on our company 🙌🏻 ).
=> getHeaders()

tests/SimpleExcelReaderTest.php
Currently tests are failing because a test is trying to assert a header missing from the stub csv file.
=> Fix tests failing

composer.json, src/SimpleExcelReader.php
At this moment only closures are accepted to format the CSV-headers.
When I was testing locally, I tested this and the example below is perfectly valid:
```php
// Example using the array callable
class FormatHeader
{
public function format(string $header): string
{
return strtolower($header);
}
}
$postcodes = SimpleExcelReader::create(__DIR__.'/postcodes.csv')
->formatHeadersUsing([new FormatHeader, 'format'])
->useDelimiter(';')
->getRows();
```
To use this kind of variations, the proposed change is needed.
FYI, WordPress support this kind of callables too, without using strongly typing.
Most of the times I use `add_filter('filter_name', [$this, 'method_name'], 10, 1)` when adding filters in WordPress, where the second argument is the callable.
See: …
=> Allow all forms of callables to format header

README.md, src/SimpleExcelReader.php, tests/SimpleExcelReaderTest.php, tests/stubs/rows-without-header.csv
If you read a CSV file which does not contain a header row, you will use `noHeaderRow()`, which returns each data row with integer keys.
For example, this file:
```csv
john@example.com,john,doe
mary-jane@example.com,mary jane,doe
```
will be returned as:
```php
[
[
0 => 'john@example.com',
1 => 'john',
2 => 'doe',
],
[
0 => 'mary-jane@example.com',
1 => 'mary jane',
2 => 'doe',
],
]
```
However, if you already know what the headers should be for the file (i.e. they are defined externally), it would be nice to be able to get each data row with the correct headers.
For example, you know the headers should be `email`, `first_name` and `last_name`, so you want the above file to be returned as:
```php
[
[
'email' => 'john@example.com',
'first_name' => 'john',
'last_name' => 'doe',
],
[
'email' …
```
=> Ability to set custom headers (whether or not headers exist in the file)

src/SimpleExcelWriter.php
Adds an optional, nullable style parameter to the addRows method to allow applying styles to all the rows in the collection.  Brings parity with the singular addRow method since addRows just defers to it anyway.
=> Add optional styling when adding multiple rows to xslx

README.md, src/SimpleExcelWriter.php, tests/SimpleExcelWriterTest.php
Currently, no feature to directly add headers from the array. This PR adds `addHeaderFromArray` method to the SimpleWriter, which allows to add headers from array.
=> Added addHeaderFromArray method to the SimpleWriter

.github/workflows/php-cs-fixer.yml, .php-cs-fixer.dist.php, UPGRADE.md, composer.json, phpunit.xml.dist, src/ReaderFactory.php, src/SimpleExcelReader.php, src/SimpleExcelWriter.php, src/WriterFactory.php, tests/SimpleExcelWriterTest.php, tests/__snapshots__/files/SimpleExcelWriterTest__it_can_write_a_csv_without_bom__1.csv, tests/__snapshots__/files/SimpleExcelWriterTest__it_can_write_the_header_from_array__1.csv
openspout/openspout is at 4.8.1 by now. Their v3 does not support 8.2.
Main change on openspout/openspout v4.8 is that the Reader & Writer classes need Options (like a delimiter) when initialising them. This leads to removing `useDelimiter()` on our end. 
Also, the openspout/openspout Factory classes don't have a way to pass the Options, so they are moved to our codebase and adjusted.
More info in the Upgrade Guide!
=> V4 with PHP 8.2 support

README.md
Documentation Correction : https://github.com/spatie/simple-excel#adding-layout
StyleBuilder() is deprecated.
Instead use Style() and new Namespace 
From (https://github.com/openspout/openspout/blob/4.x/docs/documentation.md#styling-rows)
=> Doc Correction : adding-layout

README.md
Updated OpenSpout Documentation Link to 4.x
Added Border() example to the "Adding layout" section
=> Doc Update : OpenSpout Doc Link from 3.x to 4.x and How to make border

src/SimpleExcelWriter.php
With the 3.0 release the [`useDelimiter()` was removed](https://github.com/spatie/simple-excel/blob/main/UPGRADE.md#removed-usedelimiter-on-simpleexcelwriter). This PR allows defining a delimiter when using the `streamDownload` method.
Prior 3.x
```php
SimpleExcelWriter::streamDownload('your-export.csv')
->useDelimiter(';')
->addRow([
'first_name' => 'John',
'last_name' => 'Doe',
])
->addRow([
'first_name' => 'Jane',
'last_name' => 'Doe',
])
->toBrowser();
```
3.x
```php
SimpleExcelWriter::streamDownload(downloadName: 'your-export.csv', delimiter: ';')
->addRow([
'first_name' => 'John',
'last_name' => 'Doe',
])
->addRow([
'first_name' => 'Jane',
'last_name' => 'Doe',
])
->toBrowser();
```
=> Allow delimiter in streamDownload()

src/SimpleExcelWriter.php
In 2.x you can disable `BOM` like that:
```php
$writer = SimpleExcelWriter::streamDownload('file.csv', 'csv', function ($writer) {
$writer->setShouldAddBOM(false);
});
```
But in 3.x it isn't possible.
This PR allows defining a `shouldAddBom` when using the streamDownload method.
=> Allow `shouldAddBom` in `streamDownload`

README.md
Just stumbled upon the task to change the default column widths and row heights for generated Excel files. Thought I'd share the way on how to do it here.
=> Add some documentation to explain how to change column widths

README.md
I came across a situation where I was trying to write to an Excel file but the file was empty. The reason was that for Excel files the file doesn't get written until the destructor is called. So I figured I'll make a PR to add it to the documentation.
=> Add documentation for closing the file manually when necessary

.github/workflows/run-tests.yml, README.md, composer.json, src/SimpleExcelReader.php
Openspout 4.16 introduced a change that returns formulas verbatim instead of interpreting the result (see openspout/openspout#169).
This PR prevents this BC change for simple-excel users while introducing a new `keepFormulas` method that allows for the new openspout behavior.
The new minimum version of openspout has been set to 4.19 because interim versions added several fixes to the formula behavior.
=> Fix openspout backwards compatibility change that stops parsing formulas

README.md, src/SimpleExcelReader.php, tests/SimpleExcelReaderTest.php
When using the package to read invoices, I came across the issue where some invoices didn't have a certain sheet. So I added the possibility to check if the sheets exists.
```php  
$sheetExists = SimpleExcelReader::create($pathToXlsx)
->sheetExists("sheet1");
```
=> Add the option to check if a sheet exists by name

README.md, src/SimpleExcelWriter.php
If we use callback to write content, we must open the OpenSpout writer. So it basically calls twice, which makes problem on CSV.
`openToBrowser` function also need the file name inside closure. So I've added the `$downloadName` as an argument.
=> CSV stream callback fixed

src/SimpleExcelReader.php, src/SimpleExcelWriter.php
Since PHP 8.4 Implicitly marking parameters as nullable is deprecated, the explicit nullable type must be used instead.
For example change `Style $style = null` => `?Style $style = null`
=> Fix deprecation warning for PHP 8.4 implicit nullable parameter

src/SimpleExcelReader.php, tests/SimpleExcelReaderTest.php
In order to be able to count and retrieve data from the same lazy collection (use case; add a filter to the lazy collection returned by `getRows()` and pass that on), it has to rewind the `rowIterator` to after the header
=> Rewind iterator after use
